services:
  nodejs:
    image: node:20
    container_name: ecagenthub
    restart: 'no'
    working_dir: /var/www/html
    ports:
      - "9154:3000"
    volumes:
      - ./:/var/www/html
    command: sh -c "cp -n .env.prod .env && npm install && npm run dev"
