services:
  nodejs:
    image: node:20
    container_name: ecagenthub
    restart: 'no'
    working_dir: /var/www/html
    ports:
      - "9154:3000"
    volumes:
      - ./:/var/www/html
    command: sh -c "npm install && npm run dev"
    extra_hosts:
      - "api.ecagenthub.loc:172.19.0.2" # направляем на nginx-proxy и делаем bind в /etc/hosts
    networks:
      - nginx_proxy
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0 # только для локальной разработки, для отключения проверки SSL/TLS
networks:
  nginx_proxy:
    external: true